name: Push to PypiServer

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      with:
        ref: main # Replace with the name of the default branch of your fork
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        fetch-depth: 0
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Fetch Upstream Tag version
      run: |
        git remote add upstream https://github.com/MarketSquare/robotframework-browser.git
        git fetch upstream --tags
    - name: Dependencies for building docs # TODO: thin a bit
      run: |
        npm ci
        python -m pip install --upgrade pip
        pip install -r Browser/dev-requirements.txt
        export VERSION=$(git describe --tags --abbrev=0)
        inv build
        python setup.py sdist
    
    - name: Install Twine
      run: |
        python -m pip install twine
        
    - name: Upload Package to PyPI Server
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        twine upload --repository-url ${{ secrets.PYPISERVER }} https://pypiserver.paipaya.com dist/*.tar.gz

