name: Push to PypiServer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: omen-ubuntu
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      with:
        ref: main # Replace with the name of the default branch of your fork
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        fetch-depth: 0
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    # Python 3.9 is already installed
    - name: Fetch Upstream Tag version
      run: |
        git remote add upstream https://github.com/MarketSquare/robotframework-browser.git
        git fetch upstream --tags
    - name: Dependencies for building docs # TODO: thin a bit. Run in bash because of alias
      run: |
        alias python=python3  
        npm ci
        python bootstrap.py
        source .venv/bin/activate
        inv deps
        export VERSION=$(git describe --tags --abbrev=0)
        inv version $VERSION
        inv build
        inv release || true
      shell: bash
    - name: Install Twine
      run: |
        python -m pip install twine
        
    - name: Upload Package to PyPI Server
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        twine upload --repository-url ${{ secrets.PYPISERVER }} dist/*.whl

