name: Publish to GitHub Release

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      with:
        ref: main # Replace with the name of the default branch of your fork
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        fetch-depth: 0
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Dependencies for building docs # TODO: thin a bit
      run: |
        npm ci
        python -m pip install --upgrade pip
        pip install -r Browser/dev-requirements.txt
        export VERSION=${{ github.event.release.tag_name }}
        inv build
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.tar.gz
        asset_name: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.tar.gz
        asset_content_type: application/gzip
